// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Run: dart pub global activate flutterfire_cli

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdxKkxVNm0M9qZlXbexfmkmiQRrC9WyAA',
    appId: '1:635829133596:android:e251ef5d368e919dc79ad9',
    messagingSenderId: '635829133596',
    projectId: 'trimurti-dairy-92591',
    storageBucket: 'trimurti-dairy-92591.firebasestorage.app',
  );

  // Then: flutterfire configure

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh74JdQYNs4cE_Pw8z6JuC5aC6Yz7Ylwc',
    appId: '1:635829133596:ios:ccd41088f6859642c79ad9',
    messagingSenderId: '635829133596',
    projectId: 'trimurti-dairy-92591',
    storageBucket: 'trimurti-dairy-92591.firebasestorage.app',
    iosBundleId: 'com.example.trimurtiDairy',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRJwqlHuVw-bqYeRdp19-ynegRlQ3Xb1E',
    appId: '1:635829133596:web:a90f819e0140f441c79ad9',
    messagingSenderId: '635829133596',
    projectId: 'trimurti-dairy-92591',
    authDomain: 'trimurti-dairy-92591.firebaseapp.com',
    storageBucket: 'trimurti-dairy-92591.firebasestorage.app',
    measurementId: 'G-XWE2K53ZR9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAh74JdQYNs4cE_Pw8z6JuC5aC6Yz7Ylwc',
    appId: '1:635829133596:ios:ccd41088f6859642c79ad9',
    messagingSenderId: '635829133596',
    projectId: 'trimurti-dairy-92591',
    storageBucket: 'trimurti-dairy-92591.firebasestorage.app',
    iosBundleId: 'com.example.trimurtiDairy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRJwqlHuVw-bqYeRdp19-ynegRlQ3Xb1E',
    appId: '1:635829133596:web:48a0334b53fcd6ccc79ad9',
    messagingSenderId: '635829133596',
    projectId: 'trimurti-dairy-92591',
    authDomain: 'trimurti-dairy-92591.firebaseapp.com',
    storageBucket: 'trimurti-dairy-92591.firebasestorage.app',
    measurementId: 'G-5VK7LH0ZC5',
  );

}